# This file was generated by GoReleaser. DO NOT EDIT.
cask "scriva" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "bb7ec898496dcccc9d2df9fef81b833efa54abbab5287d0c582438ff1db8346f"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f9e4fa248e031c70cfcdbf87bf766537281340b79a1ba08893423046fbf3536"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62506c5ca975fa61b32df037f6a41e689d50cd702f69bc5bd471fef322d88d91"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "73a0ff9486225d66b470625760b36dcafa743b2da2c605e0c24c60fedef4d1d6"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scriva"
  desc "ScrivaDB — an embedded append-only document database"
  homepage "https://github.com/srjn45/scriva"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scriva"
  binary "scriva-cli"

  # No zap stanza required

end
