# This file was generated by GoReleaser. DO NOT EDIT.
cask "scriva" do
  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "abce346567c79ea933717be8de1553cda67bbdbcac7420325be068fcb35563b4"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2f59184cd850a0c1b5fbca6e2853a27791c450f361f98e654a3fd658dc19e15"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "393138b0d0e842c8c5eee43d88681d87132a80ce71351f8534f42ad635c291a8"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8938f3f7756dc3fe017e73cbdb1fec062947145f6a0945dc55177e0b9f532b64"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_linux_amd64.tar.gz"
    end
  end

  name "scriva"
  desc "ScrivaDB — an embedded append-only document database"
  homepage "https://github.com/srjn45/scriva"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scriva"
  binary "scriva-cli"

  # No zap stanza required
end
