# This file was generated by GoReleaser. DO NOT EDIT.
cask "scriva" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "d511e62d4fc1b142868ea94e0436065f8ed2d88690e93cbefd671d687934b8ed"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0244769a92cd4a07075ed500ddb0c78504eac6758ed5fa09d5d46bcb183e532"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "945a58d2f94b825e5409446425755c296d5ac9d7986bfaec262349053323ce07"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "68bd619b881122017d6cc5aecbbdec85af401f98c6d4d34eae16956f756e8a7e"
      url "https://github.com/srjn45/scriva/releases/download/v#{version}/scriva_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scriva"
  desc "ScrivaDB — an embedded append-only document database"
  homepage "https://github.com/srjn45/scriva"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scriva"
  binary "scriva-cli"

  # No zap stanza required

end
